import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Layout from '@/components/layout'
import { StickyNavbar } from '@/components/header'
import Footer from '@/components/footer'
const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-poppins"
})

export const metadata = {
  title: 'Nombox',
  description: 'Generated by create next app',
  icons: {
    icon: "/logo/nombox.svg",
    apple: "/logo/nombox.svg",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.variable} bg-[#F8FBFF]`}>
        <Layout>
          {/* <StickyNavbar /> */}
          {children}
          {/* <Footer /> */}
        </Layout>
      </body>
    </html>
  )
}
